## Data-X (IEOR 190D/290): HW 2
### Nga Pui Leung
#### SID: 25237110

## Problem 1

1. Create two numpy arrays (a and b). a should be all integers between 10-19 (inclusive), and
b should be ten evenly spaced numbers between 1-7. Print all the results below:
    1. Square all the elements in both arrays (element-wise)
    2. Add both the squared arrays
    3. Sum the even elements of the added array.
    4. Take the square root of the added array (element-wise square root)
2. Append b to a, reshape the appended array so that it is a 5x4, 2d array and store the results in a variable called m. Print m.
3. Extract the second and the third column of the m matrix. Store the resulting 5x2 matrix in a new variable called m2. Print m2.
4. Take the dot product of m2T and m store the results in a matrix called m3. Print m3.
5. Round the m3 matrix to two decimal points. Store the result in place and print the new m3.
6. Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, and the lowest value is at the bottom right. Print the sorted m3 array.

In [1]:
import numpy as np

In [26]:
#Create two numpy arrays (a and b). a should be all integers between 10-19 (inclusive), and b should be ten evenly 
#spaced numbers between 1-7.
a = np.array(range(10, 20))
b = np.linspace(1, 7, 10)
a, b

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 1.        ,  1.66666667,  2.33333333,  3.        ,  3.66666667,
         4.33333333,  5.        ,  5.66666667,  6.33333333,  7.        ]))

In [27]:
#Square all the elements in both arrays (element-wise).
squares_a = a**2
squares_b = b**2
squares_a, squares_b

(array([100, 121, 144, 169, 196, 225, 256, 289, 324, 361]),
 array([  1.        ,   2.77777778,   5.44444444,   9.        ,
         13.44444444,  18.77777778,  25.        ,  32.11111111,
         40.11111111,  49.        ]))

In [28]:
#Add both the squared arrays
sum_of_squares = squares_a + squares_b
sum_of_squares

array([ 101.        ,  123.77777778,  149.44444444,  178.        ,
        209.44444444,  243.77777778,  281.        ,  321.11111111,
        364.11111111,  410.        ])

In [29]:
#Sum the even elements (indexes) of the added array.
sum(sum_of_squares[::2])

1105.0

In [30]:
#Take the square root of the added array (element-wise square root)
sum_of_squares**0.5

array([ 10.04987562,  11.12554618,  12.22474721,  13.34166406,
        14.47219556,  15.61338457,  16.76305461,  17.91957341,
        19.08169571,  20.24845673])

In [33]:
#Append b to a, reshape the appended array so that it is a 5x4, 2d array and store the results in a variable called m.
appended = np.append(a, b)
m = appended.reshape((5, 4))
m

array([[ 10.        ,  11.        ,  12.        ,  13.        ],
       [ 14.        ,  15.        ,  16.        ,  17.        ],
       [ 18.        ,  19.        ,   1.        ,   1.66666667],
       [  2.33333333,   3.        ,   3.66666667,   4.33333333],
       [  5.        ,   5.66666667,   6.33333333,   7.        ]])

In [39]:
#Extract the second and the third column of the m matrix. Store the resulting 5x2 matrix in a new variable called m2.
m2 = m[:, 2:4]
m2

array([[ 12.        ,  16.        ,   1.        ,   3.66666667,
          6.33333333],
       [ 13.        ,  17.        ,   1.66666667,   4.33333333,   7.        ]])

In [40]:
#Take the dot product of m2T and m store the results in a matrix called m3.
m3 = np.dot(m2.T, m)
m3

array([[ 402.22222222,  437.88888889,  454.55555556,  489.88888889],
       [ 443.11111111,  482.33333333,  489.88888889,  528.55555556]])

In [46]:
#Round the m3 matrix to two decimal points. Store the result in place and print the new m3.
m3 = np.round(m3, decimals=2)
m3

array([[ 402.22,  437.89,  454.56,  489.89],
       [ 443.11,  482.33,  489.89,  528.56]])

In [59]:
#Sort the m3 array so that the highest value is at the top left, the next highest value to the right of the highest, 
#and the lowest value is at the bottom right. Print the sorted m3 arrays.
sorted_m3 = np.sort(m3, axis=None)
m3 = sorted_m3.reshape((2, 4))
m3

array([[ 402.22,  437.89,  443.11,  454.56],
       [ 482.33,  489.89,  489.89,  528.56]])